### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ranslsad** [debugtitan/new-pool-solana#1]
Hello im having this error: WARNING → get_parsed_transaction 'NoneType' object has no attribute 'transaction'
on the line: data = txn.value.transaction.meta

any ideas how can i solve this?

thanks!

**Comment by debugtitan** [comment]
new update has been pushed, issue was setting private node as None

**Comment by pweeeG** [comment]
> new update has been pushed, issue was setting private node as None

I am still having the same error: WARNING → get_parsed_transaction 'NoneType' object has no attribute 'transaction'

cant figure out how to fix it, thanks in advance
